export const UNITS = [
  { value: 'g', label: 'g' },
  { value: 'kg', label: 'kg' },
  { value: 'ml', label: 'ml' },
  { value: 'dl', label: 'dl' },
  { value: 'l', label: 'l' },
  { value: 'tsk', label: 'tsk' },
  { value: 'spsk', label: 'spsk' },
  { value: 'stk', label: 'stk' },
  { value: 'fed', label: 'fed' },
  { value: 'skive', label: 'skive' },
  { value: 'bundt', label: 'bundt' },
  { value: 'håndfuld', label: 'håndfuld' },
  { value: 'knivspids', label: 'knivspids' },
  { value: 'dåse', label: 'dåse' },
  { value: 'pose', label: 'pose' },
]
